"""add material image type, drop product materials link

Revision ID: 895ae596e384
Revises: 41d128f97eaf
Create Date: 2026-07-28 17:30:23.609963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895ae596e384'
down_revision: Union[str, None] = '41d128f97eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_materials')
    op.add_column(
        'material_images',
        sa.Column('image_type', sa.String(length=20), nullable=False, server_default='fabric'),
    )
    op.alter_column('material_images', 'image_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_images', 'image_type')
    op.create_table('product_materials',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('product_materials_material_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_materials_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'material_id', name=op.f('product_materials_pkey'))
    )
    # ### end Alembic commands ###
