"""add product image thumbnail key

Revision ID: 94d9dfde1bd0
Revises: 7fbd163800f6
Create Date: 2026-07-28 13:27:46.085518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d9dfde1bd0'
down_revision: Union[str, None] = '7fbd163800f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('thumbnail_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'thumbnail_key')
    # ### end Alembic commands ###
