"""add order item completion flag

Revision ID: eaa0a6edd50d
Revises: 36db866088b2
Create Date: 2026-07-29 11:46:42.495121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa0a6edd50d'
down_revision: Union[str, None] = '36db866088b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_items',
        sa.Column('is_completed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('order_items', 'is_completed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_completed')
    # ### end Alembic commands ###
