"""add material origin field

Revision ID: fc94caa423c1
Revises: 3b1889bac526
Create Date: 2026-07-28 15:43:26.695415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc94caa423c1'
down_revision: Union[str, None] = '3b1889bac526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('origin', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'origin')
    # ### end Alembic commands ###
